### ISSUE TITLE
Issue : FailFast: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by FireHelmet** [giordyb/rundeck-powershell-plugin#1]
Hi giordyb,

I have an issue when I execute a simple command-line like write-host "Hello" or a simple script : 
![image](https://user-images.githubusercontent.com/17533298/31717320-ab754078-b40b-11e7-9f72-cd14c4075a32.png)

My Rundeck version is 2.10.0
OS : CentOS 7

I have followed the installation instruction without error.

My Rundeck XML ressource file contain for each node like frap050 : 
![image](https://user-images.githubusercontent.com/17533298/31717517-81be2bea-b40c-11e7-93a3-fa3090a099fe.png)

I'm using negotiate in Auth type

Could you help me ?

Thank you.

**Comment by FireHelmet** [comment]
@giordyb , Could you help me, please ?

Thanks !

**Comment by giordyb** [comment]
I am having the same issue after upgrading my environment to the latest rundeck & powershell versions and I think it has nothing to do with my script since it does it even if I replace everything with a write-host... it might have something to do with this: https://github.com/PowerShell/PowerShell/issues/4873

**Comment by FireHelmet** [comment]
@giordyb,

Thank you for your answer, I will do a test with PS in beta 4 and latest Rundeck version.
And do you have tested Rundeck with your plugin on Windows OS ?

Thanks !

**Comment by FireHelmet** [comment]
@giordyb The issue is solved in last powershell beta version (9). But the name of powershell binary has changed to pwsh.

![image](https://user-images.githubusercontent.com/17533298/32541514-2d6caf98-c470-11e7-9bfb-98ef5c785e67.png)
